//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartwayTest.DataAccess.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartwayTest.DataAccess.Scripts.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO 
        ///	employees (name, surname, phone, company_id, passport_id, department_id) 
        ///VALUES 
        ///	(@name, @surname, @phone, @company_id, @passport_id, @department_id) 
        ///RETURNING id.
        /// </summary>
        internal static string CreateEmployee {
            get {
                return ResourceManager.GetString("CreateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO passports (type, number)
        ///VALUES (@type, @number)
        ///RETURNING id.
        /// </summary>
        internal static string CreatePassport {
            get {
                return ResourceManager.GetString("CreatePassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM employees 
        ///WHERE id = @id.
        /// </summary>
        internal static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    e.id,
        ///    e.name, 
        ///    e.surname, 
        ///    e.phone, 
        ///    e.company_id as CompanyId,
        ///    p.id as PassportId,
        ///    p.type as PassportType,
        ///    p.number as PassportNumber,
        ///    d.name as DepartmentName,
        ///    d.phone as DepartmentPhone
        ///FROM employees e
        ///    LEFT JOIN passports p ON e.passport_id = p.id
        ///    LEFT JOIN departments d ON e.department_id = d.id
        ///WHERE e.id = @id 
        ///LIMIT 1.
        /// </summary>
        internal static string GetEmployeeById {
            get {
                return ResourceManager.GetString("GetEmployeeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	e.id,
        ///	e.name, 
        ///	e.surname, 
        ///	e.phone, 
        ///	e.company_id as CompanyId,
        ///	p.type as PassportType,
        ///	p.number as PassportNumber,
        ///	d.name as DepartmentName,
        ///	d.phone as DepartmentPhone
        ///FROM employees e
        ///	LEFT JOIN passports p ON e.passport_id = p.id
        ///	LEFT JOIN departments d ON e.department_id = d.id
        ///WHERE e.company_id = @company_id.
        /// </summary>
        internal static string GetEmployeesByCompanyId {
            get {
                return ResourceManager.GetString("GetEmployeesByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	e.id,
        ///	e.name, 
        ///	e.surname, 
        ///	e.phone, 
        ///	e.company_id as CompanyId,
        ///	p.type as PassportType,
        ///	p.number as PassportNumber,
        ///	d.name as DepartmentName,
        ///	d.phone as DepartmentPhone
        ///FROM employees e
        ///	LEFT JOIN passports p ON e.passport_id = p.id
        ///	LEFT JOIN departments d ON e.department_id = d.id
        ///WHERE e.department_id = @department_id.
        /// </summary>
        internal static string GetEmployeesByDepartmentId {
            get {
                return ResourceManager.GetString("GetEmployeesByDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EXISTS(
        ///    SELECT id 
        ///    FROM companies
        ///    WHERE id = @id).
        /// </summary>
        internal static string IsCompanyByIdExists {
            get {
                return ResourceManager.GetString("IsCompanyByIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EXISTS(
        ///    SELECT id 
        ///    FROM departments
        ///    WHERE id = @id).
        /// </summary>
        internal static string IsDeparmentByIdExists {
            get {
                return ResourceManager.GetString("IsDeparmentByIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EXISTS(
        ///    SELECT id 
        ///    FROM passports
        ///    WHERE type = @type AND number = @number).
        /// </summary>
        internal static string IsPassportExists {
            get {
                return ResourceManager.GetString("IsPassportExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE employees SET
        ///    name = COALESCE(@name, name),
        ///    surname = COALESCE(@surname, surname),
        ///    phone = COALESCE(@phone, phone),
        ///    company_id = COALESCE(@company_Id, company_id),
        ///    department_id = COALESCE(@department_Id, department_id)
        ///WHERE id = @id.
        /// </summary>
        internal static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE passports SET
        ///	type = COALESCE(@type, type),
        ///	number = COALESCE(@number, number)
        ///WHERE id = @id.
        /// </summary>
        internal static string UpdatePassport {
            get {
                return ResourceManager.GetString("UpdatePassport", resourceCulture);
            }
        }
    }
}
